version: '3'

services:
  web:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "8080:8000"
    env_file: .env
    networks:
        app_net:
            ipv4_address: ${IP_SERVER}
networks:
    app_net:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: ${IP_SUBNET}